FROM node:19-alpine

WORKDIR /app

COPY . /app

COPY package.json /app/package.json

COPY package-lock.json /app/package-lock.json

RUN npm install;

RUN npm run test;

RUN npm run build;

EXPOSE 3000

CMD ["npm", "start"]

